### ISSUE TITLE
[Docs] 2월 10일 회의

### ISSUE THREAD

**Issue by eun-seong** [joa-inha/JO-PR#1]
### DONE
- 기능정의서
- 스크린보드

### 다음 회의
* 2월 20일

### TODO
- [ ] AWS 서버 열기 (프리티어)
- [ ] nginx, uWSGI 설치
- [ ] React.js 공부
- [ ] 웹 템플릿 구현

**Comment by eun-seong** [comment]
@NyangUk @Zzu-h  기능정의서와 스크린보드 링크 있으면 달아주세요
